// moderncv output: the main .tex file plus one Sections/<file>.tex per YAML
// section, all generated from the same content as the plain and Word versions.

const { texEscape, tex, contactLines, LEFTRIGHT_MACRO, lineWithRight } = require('./markup');

// Per-style document settings, and how a generic entry maps onto that style's
// \cventry arguments (each moderncv body layout uses the arguments differently).
const STYLES = {
  // moderncvstyleresume.sty: body 4 with the \cventry redefined there --
  //   \cventry{right}{heading}{}{}{}{description}
  // where `right` is drawn flush right on the heading line; the italic sub
  // line goes at the top of the description.
  resume: {
    classOptions: '10pt,letterpaper,roman,colorlinks',
    margin: '0.55in',
    titleGap: '-20pt',
    preamble: '\\setlength{\\hintscolumnwidth}{0pt}',
    entry: (e) => `\\cventry{${tex(e.right)}}{${tex(e.heading)}}{}{}{}{${entryDescription(e, true)}}`,
  },
  // moderncvstylebanking2.sty, with the \cventry redefined there --
  //   \cventry{sub_right}{sub}{heading}{right}{}{description}
  // draws a bold heading/right line, then an italic sub/sub_right line.
  banking2: {
    classOptions: '10pt,letterpaper,roman,colorlinks',
    margin: '0.6in',
    titleGap: '-20pt',
    preamble: '',
    entry: (e) => `\\cventry{${tex(e.sub_right)}}{${tex(e.sub)}}{${tex(e.heading)}}{${tex(e.right)}}{}{${entryDescription(e, false)}}`,
  },
};

// Everything below the entry's heading line(s): optionally the italic sub
// line, then intro, detail lines and bullets, in the same order as the plain
// version. moderncv defines \cventry with \renewcommand* (no \par allowed in
// its arguments), so paragraph ends are written as \endgraf, its synonym.
function entryDescription(e, withSub) {
  const out = [];
  if (withSub && (e.sub || e.sub_right)) out.push(lineWithRight(`\\textit{${tex(e.sub)}}`, e.sub_right, '\\endgraf'));
  if (e.intro) out.push(`${tex(e.intro)}\\endgraf`);
  for (const d of e.details || []) out.push(`${tex(d)}\\endgraf`);
  if (e.bullets && e.bullets.length) {
    out.push(['\\begin{itemize}', ...e.bullets.map((b) => `  \\item{} ${tex(b)}`), '\\end{itemize}'].join('\n'));
  }
  return out.length ? `%\n${out.join('\n')}\n` : '';
}

function sectionBody(s, style) {
  const out = [];
  if (s.paragraph) out.push(`\\cvitem{}{${tex(s.paragraph)}}`);
  for (const k of s.skills || []) out.push(`\\cvitem{${tex(k.label)}}{${tex(k.text)}}`);
  for (const e of s.entries || []) out.push(style.entry(e));
  // plain itemize, so list bullets match the entry bullets (moderncv's
  // \cvlistitem sizes its bullet column for the icon set's original symbol)
  if (s.list && s.list.length) {
    out.push(['\\cvitem{}{\\begin{itemize}', ...s.list.map((i) => `  \\item{} ${tex(typeof i === 'string' ? i : i.text)}`), '\\end{itemize}}'].join('\n'));
  }
  for (const sub of s.subsections || []) {
    out.push(`\\subsection{${tex(sub.title)}}`, sectionBody(sub, style));
  }
  return out.join('\n');
}

const banner = (srcName) =>
  `% Generated by tools/build.js from ${srcName} -- edit the YAML, not this file.\n`;

// Returns [{ path, content }] relative to the repo root.
function buildModerncv(doc, srcName) {
  const cfg = doc.moderncv;
  const style = STYLES[cfg.style];
  if (!style) throw new Error(`moderncv.style "${cfg.style}" is not one of: ${Object.keys(STYLES).join(', ')}`);
  const dir = cfg.sections_dir || 'Sections';

  const files = [];
  const inputs = [];
  for (const s of doc.sections) {
    // `manual: <file>` -- the moderncv version \inputs that hand-edited file
    // as-is (e.g. a bibliography with its own macros); the plain and Word
    // versions still render the section from the YAML.
    if (s.manual) {
      inputs.push(`\\input{${dir}/${s.manual}}`);
      continue;
    }
    if (!s.file) throw new Error(`section "${s.title}" needs a \`file:\` (or \`manual:\`) for the moderncv output`);
    files.push({
      path: `${dir}/${s.file}.tex`,
      content: `${banner(srcName)}\\section{${tex(s.title)}}\n${sectionBody(s, style)}\n`,
    });
    inputs.push(`\\input{${dir}/${s.file}}`);
  }

  // moderncv's head prints \address on its own line, then \extrainfo below it,
  // so one contact line goes in \extrainfo and two lines use both.
  const lines = contactLines(doc.contact).map((line) => line.map(tex).join('~\\textbar~'));
  if (lines.length > 2) throw new Error('the moderncv header fits at most two contact lines');
  const contact = lines.length === 2
    ? `\\address{${lines[0]}}{}{}\n\\extrainfo{${lines[1]}}`
    : `\\extrainfo{${lines[0]}}`;

  const title = `${texEscape(doc.name)}, ${texEscape(doc.credentials)}`;
  files.push({
    path: `${cfg.output}.tex`,
    content: `${banner(srcName)}\\documentclass[${style.classOptions}]{moderncv}
\\moderncvstyle{${cfg.style}}
\\moderncvcolor{black}
\\nopagenumbers{}

\\usepackage[utf8]{inputenc}
\\usepackage{lmodern}
\\usepackage[margin=${style.margin}]{geometry}
\\AtBeginDocument{\\recomputelengths}
${style.preamble}

% map every glyph (including ligatures) to Unicode so text extraction is exact
\\input{glyphtounicode}
\\pdfgentounicode=1

${LEFTRIGHT_MACRO}
${cfg.preamble ? `\n% from the YAML's moderncv.preamble\n${cfg.preamble.join('\n')}\n` : ''}
\\name{}{${texEscape(doc.name).replace(/ /g, '~')}}
\\title{${texEscape(doc.credentials)}}
${contact}

\\AfterPreamble{\\hypersetup{citecolor=black, urlcolor=blue,
  pdftitle={${title}}, pdfauthor={${texEscape(doc.name)}}}}

\\begin{document}

\\makecvtitle%
\\vspace{${style.titleGap}}

${inputs.join('\n')}

\\end{document}
`,
  });
  return files;
}

module.exports = { buildModerncv };
