// moderncv output: the main .tex file plus one Sections/<file>.tex per YAML
// section, all generated from the same content as the plain and Word versions.

const { texEscape, tex, contactLines, LEFTRIGHT_MACRO, lineWithRight } = require('./markup');

// Per-style document settings, and how a generic entry maps onto that style's
// \cventry arguments (each moderncv body layout uses the arguments differently).
const STYLES = {
  // moderncvstyleresume.sty: body 4 with the \cventry redefined there --
  //   \cventry{right}{heading}{}{}{}{description}
  // where `right` is drawn flush right on the heading line.
  resume: {
    classOptions: '10pt,letterpaper,roman,colorlinks,linkcolor=true',
    margin: '0.55in',
    titleGap: '-20pt',
    entry: (e, desc) => `\\cventry{${tex(e.right)}}{${tex(e.heading)}}{}{}{}{${desc}}`,
  },
};

// Everything below the entry's heading line: the italic sub line, intro,
// detail lines and bullets, in the same order as the plain version.
// moderncv defines \cventry with \renewcommand* (no \par allowed in its
// arguments), so paragraph ends are written as \endgraf, its synonym.
function entryDescription(e) {
  const out = [];
  if (e.sub || e.sub_right) out.push(lineWithRight(`\\textit{${tex(e.sub)}}`, e.sub_right, '\\endgraf'));
  if (e.intro) out.push(`${tex(e.intro)}\\endgraf`);
  for (const d of e.details || []) out.push(`${tex(d)}\\endgraf`);
  if (e.bullets && e.bullets.length) {
    out.push(['\\begin{itemize}', ...e.bullets.map((b) => `  \\item{} ${tex(b)}`), '\\end{itemize}'].join('\n'));
  }
  return out.length ? `%\n${out.join('\n')}\n` : '';
}

function sectionBody(s, style) {
  const out = [];
  if (s.paragraph) out.push(`\\cvitem{}{${tex(s.paragraph)}}`);
  for (const k of s.skills || []) out.push(`\\cvitem{${tex(k.label)}}{${tex(k.text)}}`);
  for (const e of s.entries || []) out.push(style.entry(e, entryDescription(e)));
  for (const item of s.list || []) out.push(`\\cvlistitem{${tex(item)}}`);
  for (const sub of s.subsections || []) {
    out.push(`\\subsection{${tex(sub.title)}}`, sectionBody(sub, style));
  }
  return out.join('\n');
}

const banner = (srcName) =>
  `% Generated by tools/build.js from ${srcName} -- edit the YAML, not this file.\n`;

// Returns [{ path, content }] relative to the repo root.
function buildModerncv(doc, srcName) {
  const cfg = doc.moderncv;
  const style = STYLES[cfg.style];
  if (!style) throw new Error(`moderncv.style "${cfg.style}" is not one of: ${Object.keys(STYLES).join(', ')}`);
  const dir = cfg.sections_dir || 'Sections';

  const files = [];
  const inputs = [];
  for (const s of doc.sections) {
    if (!s.file) throw new Error(`section "${s.title}" needs a \`file:\` for the moderncv output`);
    files.push({
      path: `${dir}/${s.file}.tex`,
      content: `${banner(srcName)}\\section{${tex(s.title)}}\n${sectionBody(s, style)}\n`,
    });
    inputs.push(`\\input{${dir}/${s.file}}`);
  }

  // moderncv's head prints \address on its own line, then \extrainfo below it,
  // so one contact line goes in \extrainfo and two lines use both.
  const lines = contactLines(doc.contact).map((line) => line.map(tex).join('~\\textbar~'));
  if (lines.length > 2) throw new Error('the moderncv header fits at most two contact lines');
  const contact = lines.length === 2
    ? `\\address{${lines[0]}}{}{}\n\\extrainfo{${lines[1]}}`
    : `\\extrainfo{${lines[0]}}`;

  const title = `${texEscape(doc.name)}, ${texEscape(doc.credentials)}`;
  files.push({
    path: `${cfg.output}.tex`,
    content: `${banner(srcName)}\\documentclass[${style.classOptions}]{moderncv}
\\moderncvstyle{${cfg.style}}
\\moderncvcolor{black}
\\nopagenumbers{}

\\usepackage[utf8]{inputenc}
\\usepackage{lmodern}
\\usepackage[margin=${style.margin}]{geometry}
\\AtBeginDocument{\\recomputelengths}
\\setlength{\\hintscolumnwidth}{0pt}

% map every glyph (including ligatures) to Unicode so text extraction is exact
\\input{glyphtounicode}
\\pdfgentounicode=1

${LEFTRIGHT_MACRO}

\\name{}{${texEscape(doc.name).replace(/ /g, '~')}}
\\title{${texEscape(doc.credentials)}}
${contact}

\\AfterPreamble{\\hypersetup{citecolor=black, urlcolor=black,
  pdftitle={${title}}, pdfauthor={${texEscape(doc.name)}}}}

\\begin{document}

\\makecvtitle%
\\vspace{${style.titleGap}}

${inputs.join('\n')}

\\end{document}
`,
  });
  return files;
}

module.exports = { buildModerncv };
