// Plain single-column LaTeX output (article class, no tables).

const { texEscape, tex, contactLines, LEFTRIGHT_MACRO, lineWithRight } = require('./markup');

function texEntry(e) {
  // The heading lines are glued (\nopagebreak) to whatever follows them in the
  // same entry, but nothing is glued after the entry's last line: otherwise
  // consecutive short entries (e.g. Education) chain into one unbreakable block.
  const head = [lineWithRight(`\\textbf{${tex(e.heading)}}`, e.right)];
  if (e.sub || e.sub_right) head.push(lineWithRight(`\\textit{${tex(e.sub)}}`, e.sub_right));
  if (e.intro) head.push(`${tex(e.intro)}\\par`);
  const body = (e.details || []).map((d) => `${tex(d)}\\par`);
  if (e.bullets && e.bullets.length) {
    body.push(['\\begin{itemize}', ...e.bullets.map((b) => `  \\item{} ${tex(b)}`), '\\end{itemize}'].join('\n'));
  }
  return [...head, ...body].join('\\nopagebreak\n') + '\n\\entrygap\n';
}

// Content shared by sections and subsections.
function texBody(s) {
  const out = [];
  if (s.paragraph) out.push(`${tex(s.paragraph)}\\par`);
  if (s.skills) {
    for (const k of s.skills) out.push(`\\textbf{${tex(k.label)}:} ${tex(k.text)}\\par`);
  }
  if (s.entries) for (const e of s.entries) out.push(texEntry(e));
  if (s.list) {
    // unbulleted lists (e.g. publications that carry their own [n] labels)
    // get a hanging indent instead of a bullet
    out.push(s.unbulleted
      ? '\\begin{itemize}[label={}, leftmargin=1.5em, itemindent=-1.5em, labelwidth=0pt, labelsep=0pt]'
      : '\\begin{itemize}');
    for (const item of s.list) out.push(`  \\item{} ${tex(item)}`);
    out.push('\\end{itemize}');
  }
  for (const sub of s.subsections || []) {
    out.push(`\\cvsubsection{${tex(sub.title)}}`, texBody(sub));
  }
  return out.join('\n');
}

const texSection = (s) => `\\cvsection{${tex(s.title)}}\n${texBody(s)}`;

function buildPlainTex(doc, srcName) {
  const header = `${texEscape(doc.name)}, ${texEscape(doc.credentials)}`;
  return `% Generated by tools/build.js from ${srcName} -- edit the YAML, not this file.
\\documentclass[10pt,letterpaper]{article}
\\usepackage[T1]{fontenc}
\\usepackage[utf8]{inputenc}
\\usepackage{lmodern}
\\usepackage{textcomp}
\\usepackage[margin=0.6in]{geometry}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\hypersetup{pdftitle={${header}}, pdfauthor={${texEscape(doc.name)}}}
% map every glyph (including ligatures) to Unicode so text extraction is exact
\\input{glyphtounicode}
\\pdfgentounicode=1

\\pagestyle{empty}
\\setlength{\\parindent}{0pt}
\\setlength{\\parskip}{0pt}
\\setlength{\\emergencystretch}{3em}
\\setlist[itemize]{leftmargin=1.3em, topsep=1pt, itemsep=0.5pt, parsep=0pt}
\\newcommand{\\cvsection}[1]{%
  \\vspace{5pt}{\\large\\bfseries #1}\\par\\nopagebreak\\vspace{2pt}\\hrule
  \\nopagebreak\\vspace{3pt}\\nopagebreak}
\\newcommand{\\cvsubsection}[1]{%
  \\vspace{3pt}{\\bfseries #1}\\par\\nopagebreak\\vspace{2pt}\\nopagebreak}
\\newcommand{\\entrygap}{\\vspace{3pt}}
${LEFTRIGHT_MACRO}

\\begin{document}

\\begin{center}
  {\\LARGE\\bfseries ${header}}\\\\[3pt]
  ${contactLines(doc.contact).map((line) => line.map(tex).join(' \\textbar{} ')).join('\\\\\n  ')}
\\end{center}

${doc.sections.map(texSection).join('\n\n')}

\\end{document}
`;
}

module.exports = { buildPlainTex };
