// Builds a plain single-column LaTeX file and a Word file from one YAML
// content file, so both versions always carry identical text.
//
//   node tools/build.js content/resume.yaml
//
// Writes <output>.tex and <output>.docx next to the content/ directory
// (i.e. the repo root). Compile the .tex with pdflatex as usual.

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');
const {
  Document, Packer, Paragraph, TextRun, ExternalHyperlink, AlignmentType,
  HeadingLevel, LevelFormat, BorderStyle, Tab, TabStopType,
} = require('docx');

// ---------------------------------------------------------------- inline markup

// Splits "**bold**, *italic*, [text](url)" into styled segments.
function parseInline(str) {
  const segments = [];
  const re = /\*\*(.+?)\*\*|\*(.+?)\*|\[([^\]]+)\]\(([^)\s]+)\)/g;
  let last = 0;
  let m;
  while ((m = re.exec(str)) !== null) {
    if (m.index > last) segments.push({ text: str.slice(last, m.index) });
    if (m[1] !== undefined) segments.push({ text: m[1], bold: true });
    else if (m[2] !== undefined) segments.push({ text: m[2], italic: true });
    else segments.push({ text: m[3], url: m[4] });
    last = re.lastIndex;
  }
  if (last < str.length) segments.push({ text: str.slice(last) });
  return segments;
}

// ---------------------------------------------------------------- LaTeX

const TEX_ESCAPES = {
  '\\': '\\textbackslash{}', '&': '\\&', '%': '\\%', '$': '\\$', '#': '\\#',
  '_': '\\_', '{': '\\{', '}': '\\}', '~': '\\textasciitilde{}',
  '^': '\\textasciicircum{}',
};
const texEscape = (s) => s.replace(/[\\&%$#_{}~^]/g, (c) => TEX_ESCAPES[c]);
const texUrl = (u) => u.replace(/[%#]/g, (c) => '\\' + c);

function tex(str) {
  if (!str) return '';
  return parseInline(String(str)).map((s) => {
    const t = texEscape(s.text);
    if (s.url) return `\\href{${texUrl(s.url)}}{${t}}`;
    if (s.bold) return `\\textbf{${t}}`;
    if (s.italic) return `\\textit{${t}}`;
    return t;
  }).join('');
}

// \nopagebreak keeps an entry's heading lines on the same page as its body
const lineWithRight = (left, right) =>
  `${left}${right ? `\\hfill ${tex(right)}` : ''}\\par\\nopagebreak`;

function texEntry(e) {
  const out = [];
  out.push(lineWithRight(`\\textbf{${tex(e.heading)}}`, e.right));
  if (e.sub || e.sub_right) out.push(lineWithRight(`\\textit{${tex(e.sub)}}`, e.sub_right));
  if (e.intro) out.push(`${tex(e.intro)}\\par\\nopagebreak`);
  if (e.bullets && e.bullets.length) {
    out.push('\\begin{itemize}');
    for (const b of e.bullets) out.push(`  \\item ${tex(b)}`);
    out.push('\\end{itemize}');
  }
  return out.join('\n') + '\n\\entrygap\n';
}

function texSection(s) {
  const out = [`\\cvsection{${tex(s.title)}}`];
  if (s.paragraph) out.push(`${tex(s.paragraph)}\\par`);
  if (s.skills) {
    for (const k of s.skills) out.push(`\\textbf{${tex(k.label)}:} ${tex(k.text)}\\par`);
  }
  if (s.entries) for (const e of s.entries) out.push(texEntry(e));
  if (s.list) {
    out.push('\\begin{itemize}');
    for (const item of s.list) out.push(`  \\item ${tex(item)}`);
    out.push('\\end{itemize}');
  }
  return out.join('\n');
}

function buildTex(doc) {
  const header = `${texEscape(doc.name)}, ${texEscape(doc.credentials)}`;
  return `% Generated by tools/build.js from content/ -- edit the YAML, not this file.
\\documentclass[10pt,letterpaper]{article}
\\usepackage[T1]{fontenc}
\\usepackage[utf8]{inputenc}
\\usepackage{lmodern}
\\usepackage{textcomp}
\\usepackage[margin=0.6in]{geometry}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\hypersetup{pdftitle={${header}}, pdfauthor={${texEscape(doc.name)}}}
% map every glyph (including ligatures) to Unicode so text extraction is exact
\\input{glyphtounicode}
\\pdfgentounicode=1

\\pagestyle{empty}
\\setlength{\\parindent}{0pt}
\\setlength{\\parskip}{0pt}
\\setlength{\\emergencystretch}{3em}
\\setlist[itemize]{leftmargin=1.3em, topsep=1pt, itemsep=0.5pt, parsep=0pt}
\\newcommand{\\cvsection}[1]{%
  \\vspace{5pt}{\\large\\bfseries #1}\\par\\nopagebreak\\vspace{2pt}\\hrule
  \\nopagebreak\\vspace{3pt}\\nopagebreak}
\\newcommand{\\entrygap}{\\vspace{3pt}}

\\begin{document}

\\begin{center}
  {\\LARGE\\bfseries ${header}}\\\\[3pt]
  ${doc.contact.map(tex).join(' \\textbar{} ')}
\\end{center}

${doc.sections.map(texSection).join('\n\n')}

\\end{document}
`;
}

// ---------------------------------------------------------------- Word

const FONT = 'Calibri';
const BODY_SIZE = 20; // half-points: 10 pt
const MARGIN = 864; // 0.6 in, in DXA (1440 per inch)
const TEXT_WIDTH = 12240 - 2 * MARGIN; // US Letter width minus margins

function runs(str, base = {}) {
  if (!str) return [];
  return parseInline(String(str)).map((s) => {
    const opts = { text: s.text, bold: base.bold || s.bold, italics: base.italics || s.italic };
    if (s.url) return new ExternalHyperlink({ link: s.url, children: [new TextRun(opts)] });
    return new TextRun(opts);
  });
}

// A plain right-aligned tab stop at the right margin. (Word's "positional
// tab" is ignored by LibreOffice and some converters, which then run the date
// into the title.)
function lineParagraph(left, right, leftStyle, keepNext = true) {
  const children = [...runs(left, leftStyle)];
  if (right) children.push(new TextRun({ children: [new Tab()] }), ...runs(right));
  return new Paragraph({
    children, keepNext, spacing: { after: 0 },
    tabStops: [{ type: TabStopType.RIGHT, position: TEXT_WIDTH }],
  });
}

const bullet = (text) => new Paragraph({
  children: runs(text), numbering: { reference: 'bullets', level: 0 }, spacing: { after: 20 },
});

function docxSection(s) {
  const out = [new Paragraph({ text: s.title, heading: HeadingLevel.HEADING_1 })];
  if (s.paragraph) out.push(new Paragraph({ children: runs(s.paragraph) }));
  if (s.skills) {
    for (const k of s.skills) {
      out.push(new Paragraph({
        children: [new TextRun({ text: `${k.label}: `, bold: true }), ...runs(k.text)],
        spacing: { after: 30 },
      }));
    }
  }
  if (s.entries) {
    for (const e of s.entries) {
      out.push(lineParagraph(e.heading, e.right, { bold: true }));
      if (e.sub || e.sub_right) out.push(lineParagraph(e.sub, e.sub_right, { italics: true }));
      if (e.intro) out.push(new Paragraph({ children: runs(e.intro), keepNext: true, spacing: { after: 20 } }));
      for (const b of e.bullets || []) out.push(bullet(b));
      out.push(new Paragraph({ children: [], spacing: { after: 0 }, style: 'EntryGap' }));
    }
  }
  if (s.list) for (const item of s.list) out.push(bullet(item));
  return out;
}

function buildDocx(doc) {
  const header = `${doc.name}, ${doc.credentials}`;
  const contactRuns = [];
  doc.contact.forEach((c, i) => {
    if (i) contactRuns.push(new TextRun({ text: '  |  ' }));
    contactRuns.push(...runs(c));
  });
  return new Document({
    creator: doc.name,
    title: header,
    styles: {
      default: { document: { run: { font: FONT, size: BODY_SIZE } } },
      paragraphStyles: [
        {
          id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true,
          run: { font: FONT, size: 24, bold: true, color: '000000' },
          paragraph: {
            spacing: { before: 140, after: 60 }, keepNext: true, outlineLevel: 0,
            border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: '000000', space: 1 } },
          },
        },
        {
          id: 'EntryGap', name: 'Entry Gap', basedOn: 'Normal',
          run: { size: 8 }, paragraph: { spacing: { before: 0, after: 0, line: 120 } },
        },
      ],
    },
    numbering: {
      config: [{
        reference: 'bullets',
        levels: [{
          level: 0, format: LevelFormat.BULLET, text: '•', alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 300, hanging: 220 } } },
        }],
      }],
    },
    sections: [{
      properties: {
        page: {
          size: { width: 12240, height: 15840 }, // US Letter
          margin: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN },
        },
      },
      children: [
        new Paragraph({
          alignment: AlignmentType.CENTER, spacing: { after: 40 },
          children: [new TextRun({ text: header, bold: true, size: 36 })],
        }),
        new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 60 }, children: contactRuns }),
        ...doc.sections.flatMap(docxSection),
      ],
    }],
  });
}

// ---------------------------------------------------------------- main

async function main() {
  const src = process.argv[2];
  if (!src) {
    console.error('usage: node tools/build.js content/<file>.yaml');
    process.exit(1);
  }
  const doc = yaml.load(fs.readFileSync(src, 'utf8'));
  const outBase = path.resolve(path.dirname(src), '..', doc.output);
  fs.writeFileSync(`${outBase}.tex`, buildTex(doc));
  fs.writeFileSync(`${outBase}.docx`, await Packer.toBuffer(buildDocx(doc)));
  console.log(`wrote ${outBase}.tex and ${outBase}.docx`);
}

main().catch((err) => { console.error(err); process.exit(1); });
